# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_trips', to='login.User'),
        ),
    ]
