# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('plans', '0002_trip_joiner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joiner',
        ),
        migrations.AddField(
            model_name='trip',
            name='joiners',
            field=models.ManyToManyField(blank=True, null=True, to='login.User'),
        ),
    ]
